name: draggable_fab
description: A Flutter Simple Draggable Fab
version: 0.0.1
homepage: https://github.com/voyages-sncf-technologies/draggable_fab

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
 uses-material-design: true
